### ISSUE TITLE
Awesome grammar.

### ISSUE THREAD

**Issue by kach** [andrejewski/truth-table#1]
Hi! I wrote nearley, the parser generator that truth-table uses. I really love the logic grammar you wrote: it matches the "nearley vision" so well. Can I link to this project from nearley's homepage as an example?

P.S. Great project! I remember De Morgan's laws were a big part of the AP CS test… this would be an awesome project to play with that stuff. :-)

**Comment by andrejewski** [comment]
Of course, you certainly can! Thank you for writing nearley, I wish I had known about it before I wrote most of my parsers. It's so much safer and more intuitive than rolling my own.

Funny thing is I wrote this project to demonstrate DeMorgan's laws before I actually knew what they were called. When I taught AP students, I just called them simple distribution tricks. Now taking Discrete Math in college, I finally have the name for them.

**Comment by kach** [comment]
Nice, I put a link on http://nearley.js.org. Thanks again. :-)
